<?php

// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

declare(strict_types=1);

namespace SigWise\Resources;

use SigWise\SigWiseException;
use SigWise\Client;
use SigWise\ConnectionException;
use SigWise\Types;

/**
 * Create, rotate and revoke the keys your integrations sign requests with.
 *
 * @phpstan-import-type ApiKey from Types
 * @phpstan-import-type ApiKeyCreate from Types
 * @phpstan-import-type ApiKeyList from Types
 * @phpstan-import-type ApiKeySecret from Types
 * @phpstan-import-type ApiKeyUpdate from Types
 */
final class ApiKeys
{
    /** @internal Use the resources on SigWise\Client. */
    public function __construct(private readonly Client $client)
    {
    }

    /**
     * List API keys.
     *
     * Revoked keys are not listed. Secrets are never returned.
     *
     * `GET /v1/api_keys`
     *
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return ApiKeyList
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function list(array $options = []): array
    {
        /** @var ApiKeyList $result */
        $result = $this->client->request('GET', '/v1/api_keys', [], null, null, $options);

        return $result;
    }

    /**
     * Create an API key.
     *
     * Mints a key ID and signing secret. **The secret is shown only once.**
     *
     * `POST /v1/api_keys`
     *
     * @param ApiKeyCreate $body
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return ApiKeySecret
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function create(array $body, array $options = []): array
    {
        /** @var ApiKeySecret $result */
        $result = $this->client->request('POST', '/v1/api_keys', [], null, $body, $options);

        return $result;
    }

    /**
     * Update an API key.
     *
     * Rename a key, or deactivate and reactivate it. Use `DELETE` to revoke.
     *
     * `PATCH /v1/api_keys/{key_id}`
     *
     * @param ApiKeyUpdate $body
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return ApiKey
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function update(string $keyId, array $body, array $options = []): array
    {
        /** @var ApiKey $result */
        $result = $this->client->request('PATCH', '/v1/api_keys/{key_id}', ['key_id' => $keyId], null, $body, $options);

        return $result;
    }

    /**
     * Revoke an API key.
     *
     * The key stops authenticating immediately. Its ID is never reissued.
     *
     * `DELETE /v1/api_keys/{key_id}`
     *
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return void
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function revoke(string $keyId, array $options = []): void
    {
        $this->client->request('DELETE', '/v1/api_keys/{key_id}', ['key_id' => $keyId], null, null, $options);
    }

    /**
     * Rotate an API key's secret.
     *
     * Keeps the key ID and replaces the secret. The old secret stops working
     * immediately; the new one is returned only once.
     *
     * `POST /v1/api_keys/{key_id}/rotate`
     *
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return ApiKeySecret
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function rotate(string $keyId, array $options = []): array
    {
        /** @var ApiKeySecret $result */
        $result = $this->client->request('POST', '/v1/api_keys/{key_id}/rotate', ['key_id' => $keyId], null, null, $options);

        return $result;
    }
}
