<?php

// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

declare(strict_types=1);

namespace SigWise\Resources;

use SigWise\SigWiseException;
use SigWise\Client;
use SigWise\ConnectionException;
use SigWise\Types;

/**
 * Prepaid balance, the billing ledger, and card top-ups.
 *
 * @phpstan-import-type Balance from Types
 * @phpstan-import-type CheckoutCreate from Types
 * @phpstan-import-type CheckoutSession from Types
 * @phpstan-import-type CheckoutStatus from Types
 * @phpstan-import-type LedgerPage from Types
 */
final class Billing
{
    /** @internal Use the resources on SigWise\Client. */
    public function __construct(private readonly Client $client)
    {
    }

    /**
     * Get the prepaid balance.
     *
     * `GET /v1/billing`
     *
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return Balance
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function getBalance(array $options = []): array
    {
        /** @var Balance $result */
        $result = $this->client->request('GET', '/v1/billing', [], null, null, $options);

        return $result;
    }

    /**
     * List ledger entries.
     *
     * One page of the billing ledger, newest first. Pass the previous page's
     * `next_cursor` as `cursor` to continue; it is empty on the last page.
     *
     * `GET /v1/billing/ledger`
     *
     * @param array{type?: 'credit'|'charge', limit?: int, cursor?: string} $params
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return LedgerPage
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function listLedger(array $params = [], array $options = []): array
    {
        /** @var LedgerPage $result */
        $result = $this->client->request('GET', '/v1/billing/ledger', [], $params, null, $options);

        return $result;
    }

    /**
     * Start a card top-up.
     *
     * Creates a hosted Stripe Checkout Session for the amount and returns its URL. The
     * balance is credited only once Stripe confirms the payment. Returns `503` when
     * card payments are not configured.
     *
     * `POST /v1/billing/checkout`
     *
     * @param CheckoutCreate $body
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return CheckoutSession
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function createCheckout(array $body, array $options = []): array
    {
        /** @var CheckoutSession $result */
        $result = $this->client->request('POST', '/v1/billing/checkout', [], null, $body, $options);

        return $result;
    }

    /**
     * Get a top-up's status.
     *
     * Whether the Checkout Session's payment has been credited to the balance yet.
     *
     * `GET /v1/billing/checkout/{session_id}`
     *
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return CheckoutStatus
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function getCheckout(string $sessionId, array $options = []): array
    {
        /** @var CheckoutStatus $result */
        $result = $this->client->request('GET', '/v1/billing/checkout/{session_id}', ['session_id' => $sessionId], null, null, $options);

        return $result;
    }
}
