<?php

// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

declare(strict_types=1);

namespace SigWise\Resources;

use SigWise\SigWiseException;
use SigWise\Client;
use SigWise\ConnectionException;
use SigWise\Types;

/**
 * Events and messages are the evidence an object's answers are computed from.
 *
 * @phpstan-import-type EventList from Types
 * @phpstan-import-type IngestAccepted from Types
 * @phpstan-import-type IngestRequest from Types
 * @phpstan-import-type ModerationVerdict from Types
 */
final class Events
{
    /** @internal Use the resources on SigWise\Client. */
    public function __construct(private readonly Client $client)
    {
    }

    /**
     * Ingest events.
     *
     * Records one or more events or messages about an object.
     *
     * **Asynchronous (default).** Returns `202` immediately and schedules a debounced
     * analysis: a burst of events for one object coalesces into a single analysis once
     * activity settles. Read the answers with `GET /v1/objects/{object_id}` or receive
     * them by webhook.
     *
     * **Synchronous (`wait: true`).** Blocks on the analyzer and returns the verdict
     * inline with `200`, so you can approve, review or block content before publishing
     * it. Restrict scoring to some signals with `signals`, and score the request's
     * events in isolation with `include_history: false`.
     *
     * Returns `402` when the tenant's balance is empty. A synchronous request returns
     * `429` when the account already has the maximum number of synchronous analyses in
     * flight (8 by default), and `503` with `analyzer_busy` when the analyzer is
     * throttling; the events are recorded either way, so don't resend them: after
     * `Retry-After`, request an analysis with `POST /v1/objects/{object_id}/analyze`
     * and read the answers with `GET /v1/objects/{object_id}` or by webhook.
     *
     * **Safe retries.** Send an `Idempotency-Key` header (any unique string, such as a
     * UUID) and retry with the same key after a timeout or a `5xx`: the events are
     * recorded once. A repeat of an asynchronous request is answered like the first
     * and carries `Idempotent-Replayed: true`. A repeat of a synchronous request
     * returns `409` without analyzing (or charging) again; read the verdict with `GET
     * /v1/objects/{object_id}`. Reusing a key for a different object returns `422`.
     * Keys are remembered for 24 hours.
     *
     * `POST /v1/objects/{object_id}/events`
     *
     * @param IngestRequest $body
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return ModerationVerdict|IngestAccepted
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function ingest(string $objectId, array $body, array $options = []): array
    {
        /** @var ModerationVerdict|IngestAccepted $result */
        $result = $this->client->request('POST', '/v1/objects/{object_id}/events', ['object_id' => $objectId], null, $body, $options);

        return $result;
    }

    /**
     * List an object's events.
     *
     * Returns up to the 200 most recent events and messages recorded for the object,
     * newest first.
     *
     * `GET /v1/objects/{object_id}/events`
     *
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return EventList
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function list(string $objectId, array $options = []): array
    {
        /** @var EventList $result */
        $result = $this->client->request('GET', '/v1/objects/{object_id}/events', ['object_id' => $objectId], null, null, $options);

        return $result;
    }
}
