<?php

// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

declare(strict_types=1);

namespace SigWise\Resources;

use SigWise\SigWiseException;
use SigWise\Client;
use SigWise\ConnectionException;
use SigWise\Types;

/**
 * The authenticated principal and tenant settings.
 *
 * @phpstan-import-type Me from Types as MeData
 */
final class Me
{
    /** @internal Use the resources on SigWise\Client. */
    public function __construct(private readonly Client $client)
    {
    }

    /**
     * Get the current principal.
     *
     * Returns the tenant the credential belongs to. For console tokens it also returns
     * the signed-in user and whether they finished onboarding.
     *
     * `GET /v1/me`
     *
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return MeData
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function get(array $options = []): array
    {
        /** @var MeData $result */
        $result = $this->client->request('GET', '/v1/me', [], null, null, $options);

        return $result;
    }
}
