<?php

// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

declare(strict_types=1);

namespace SigWise\Resources;

use SigWise\SigWiseException;
use SigWise\Client;
use SigWise\ConnectionException;
use SigWise\Types;

/**
 * An object is anything you want answers about: a user, a listing, an order.
 *
 * @phpstan-import-type AnalyzeAllScheduled from Types
 * @phpstan-import-type AnalyzeScheduled from Types
 * @phpstan-import-type ObjectAnalysis from Types
 * @phpstan-import-type ObjectList from Types
 * @phpstan-import-type ObjectState from Types
 */
final class Objects
{
    /** @internal Use the resources on SigWise\Client. */
    public function __construct(private readonly Client $client)
    {
    }

    /**
     * Re-analyze every object.
     *
     * Schedules a re-analysis of every object the tenant has, typically after changing
     * signal configuration. Jobs run at bulk priority, behind live traffic. Each
     * analysis is billed.
     *
     * `POST /v1/analyze`
     *
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return AnalyzeAllScheduled
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function analyzeAll(array $options = []): array
    {
        /** @var AnalyzeAllScheduled $result */
        $result = $this->client->request('POST', '/v1/analyze', [], null, null, $options);

        return $result;
    }

    /**
     * List objects.
     *
     * Returns one page of objects with their latest analysis.
     *
     * `q` is either a substring of the object ID or display name, or a signal query
     * such as `is_scammer > 90 and trust_score < 1` (see [Search and
     * conditions](https://sigwise.ai/docs/guides/queries)).
     *
     * `GET /v1/objects`
     *
     * @param array{q?: string, sort?: 'recent'|'flagged'|'trust', limit?: int, offset?: int, cursor?: string} $params
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return ObjectList
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function list(array $params = [], array $options = []): array
    {
        /** @var ObjectList $result */
        $result = $this->client->request('GET', '/v1/objects', [], $params, null, $options);

        return $result;
    }

    /**
     * Get an object's analysis.
     *
     * Returns the latest answer for each signal computed for the object, plus the
     * configured signals that have no answer yet (`pending`).
     *
     * Reads are cached for a few seconds; the `X-Cache` header says whether this one
     * was a `HIT` or a `MISS`. Ingesting events and completed analyses invalidate the
     * cache.
     *
     * `GET /v1/objects/{object_id}`
     *
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return ObjectAnalysis
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function get(string $objectId, array $options = []): array
    {
        /** @var ObjectAnalysis $result */
        $result = $this->client->request('GET', '/v1/objects/{object_id}', ['object_id' => $objectId], null, null, $options);

        return $result;
    }

    /**
     * Get an object's compacted history.
     *
     * Older events are folded into a rolling summary so the analyzer gets a bounded
     * payload while keeping long-term signal. This returns that summary and the
     * compaction cursor.
     *
     * `GET /v1/objects/{object_id}/state`
     *
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return ObjectState
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function getState(string $objectId, array $options = []): array
    {
        /** @var ObjectState $result */
        $result = $this->client->request('GET', '/v1/objects/{object_id}/state', ['object_id' => $objectId], null, null, $options);

        return $result;
    }

    /**
     * Re-analyze an object.
     *
     * Schedules an immediate re-analysis without a new event, for example right after
     * adding a signal. Runs at live priority; poll `GET /v1/objects/{object_id}` for
     * the result. Returns `404` when the object has no events.
     *
     * `POST /v1/objects/{object_id}/analyze`
     *
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return AnalyzeScheduled
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function analyze(string $objectId, array $options = []): array
    {
        /** @var AnalyzeScheduled $result */
        $result = $this->client->request('POST', '/v1/objects/{object_id}/analyze', ['object_id' => $objectId], null, null, $options);

        return $result;
    }
}
