<?php

// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

declare(strict_types=1);

namespace SigWise\Resources;

use SigWise\SigWiseException;
use SigWise\Client;
use SigWise\ConnectionException;
use SigWise\Types;

/**
 * An object is anything you want answers about: a user, a listing, an order.
 *
 * @phpstan-import-type Overview from Types as OverviewData
 */
final class Overview
{
    /** @internal Use the resources on SigWise\Client. */
    public function __construct(private readonly Client $client)
    {
    }

    /**
     * Get tenant overview.
     *
     * Tenant-wide totals and per-signal value distributions, computed with SQL
     * aggregates.
     *
     * `GET /v1/overview`
     *
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return OverviewData
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function get(array $options = []): array
    {
        /** @var OverviewData $result */
        $result = $this->client->request('GET', '/v1/overview', [], null, null, $options);

        return $result;
    }
}
