<?php

// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

declare(strict_types=1);

namespace SigWise\Resources;

use SigWise\SigWiseException;
use SigWise\Client;
use SigWise\ConnectionException;
use SigWise\Types;

/**
 * Events and messages are the evidence an object's answers are computed from.
 *
 * @phpstan-import-type PlaygroundRequest from Types
 * @phpstan-import-type PlaygroundResult from Types
 */
final class Playground
{
    /** @internal Use the resources on SigWise\Client. */
    public function __construct(private readonly Client $client)
    {
    }

    /**
     * Try signals on sample events.
     *
     * Scores sample events against your enabled signals and returns the answers,
     * **without recording anything**: no object is created, the events and answers are
     * not stored, and no rule or webhook fires. Use it to check how your signals judge
     * content before you send real traffic, or after you change a signal's
     * instructions.
     *
     * The events are scored on their own, with no history. Restrict the run to some
     * signals with `signals`. At most 50 events per run.
     *
     * The analysis is real, so it is charged to your balance like any other and
     * counted as a synchronous analysis in your usage. Returns `402` when the balance
     * is empty, `429` when the account already has the maximum number of synchronous
     * analyses in flight, and `503` with `analyzer_busy` when the analyzer is
     * throttling.
     *
     * `POST /v1/playground`
     *
     * @param PlaygroundRequest $body
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return PlaygroundResult
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function run(array $body, array $options = []): array
    {
        /** @var PlaygroundResult $result */
        $result = $this->client->request('POST', '/v1/playground', [], null, $body, $options);

        return $result;
    }
}
