<?php

// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

declare(strict_types=1);

namespace SigWise\Resources;

use SigWise\SigWiseException;
use SigWise\Client;
use SigWise\ConnectionException;
use SigWise\Types;

/**
 * A rule fires an action (email, Slack or webhook) when an object's signal values
 * cross a line you care about, such as `is_scammer >= 90`.
 *
 * @phpstan-import-type RuleFiringList from Types
 */
final class RuleFirings
{
    /** @internal Use the resources on SigWise\Client. */
    public function __construct(private readonly Client $client)
    {
    }

    /**
     * List rule firings.
     *
     * The audit log of rule firings and their action outcomes, newest first.
     *
     * `GET /v1/rule_firings`
     *
     * @param array{rule_id?: string, object_id?: string, limit?: int} $params
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return RuleFiringList
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function list(array $params = [], array $options = []): array
    {
        /** @var RuleFiringList $result */
        $result = $this->client->request('GET', '/v1/rule_firings', [], $params, null, $options);

        return $result;
    }
}
