<?php

// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

declare(strict_types=1);

namespace SigWise\Resources;

use SigWise\SigWiseException;
use SigWise\Client;
use SigWise\ConnectionException;
use SigWise\Types;

/**
 * A rule fires an action (email, Slack or webhook) when an object's signal values
 * cross a line you care about, such as `is_scammer >= 90`.
 *
 * @phpstan-import-type Rule from Types
 * @phpstan-import-type RuleCreate from Types
 * @phpstan-import-type RuleList from Types
 * @phpstan-import-type RuleUpdate from Types
 */
final class Rules
{
    /** @internal Use the resources on SigWise\Client. */
    public function __construct(private readonly Client $client)
    {
    }

    /**
     * List rules.
     *
     * `GET /v1/rules`
     *
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return RuleList
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function list(array $options = []): array
    {
        /** @var RuleList $result */
        $result = $this->client->request('GET', '/v1/rules', [], null, null, $options);

        return $result;
    }

    /**
     * Create a rule.
     *
     * The condition is validated against the tenant's signals, and a `webhook` action
     * must reference a registered endpoint subscribed to `rule.triggered`.
     *
     * `POST /v1/rules`
     *
     * @param RuleCreate $body
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return Rule
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function create(array $body, array $options = []): array
    {
        /** @var Rule $result */
        $result = $this->client->request('POST', '/v1/rules', [], null, $body, $options);

        return $result;
    }

    /**
     * Get a rule.
     *
     * `GET /v1/rules/{rule_id}`
     *
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return Rule
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function get(string $ruleId, array $options = []): array
    {
        /** @var Rule $result */
        $result = $this->client->request('GET', '/v1/rules/{rule_id}', ['rule_id' => $ruleId], null, null, $options);

        return $result;
    }

    /**
     * Update a rule.
     *
     * Omitted fields are left unchanged. The resulting condition and action are
     * re-validated.
     *
     * `PATCH /v1/rules/{rule_id}`
     *
     * @param RuleUpdate $body
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return Rule
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function update(string $ruleId, array $body, array $options = []): array
    {
        /** @var Rule $result */
        $result = $this->client->request('PATCH', '/v1/rules/{rule_id}', ['rule_id' => $ruleId], null, $body, $options);

        return $result;
    }

    /**
     * Delete a rule.
     *
     * `DELETE /v1/rules/{rule_id}`
     *
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return void
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function delete(string $ruleId, array $options = []): void
    {
        $this->client->request('DELETE', '/v1/rules/{rule_id}', ['rule_id' => $ruleId], null, null, $options);
    }
}
