<?php

// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

declare(strict_types=1);

namespace SigWise\Resources;

use SigWise\SigWiseException;
use SigWise\Client;
use SigWise\ConnectionException;
use SigWise\Types;

/**
 * The authenticated principal and tenant settings.
 *
 * @phpstan-import-type Settings from Types as SettingsData
 * @phpstan-import-type SettingsUpdate from Types
 */
final class Settings
{
    /** @internal Use the resources on SigWise\Client. */
    public function __construct(private readonly Client $client)
    {
    }

    /**
     * Get tenant settings.
     *
     * `GET /v1/settings`
     *
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return SettingsData
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function get(array $options = []): array
    {
        /** @var SettingsData $result */
        $result = $this->client->request('GET', '/v1/settings', [], null, null, $options);

        return $result;
    }

    /**
     * Update tenant settings.
     *
     * Omitted fields are left unchanged.
     *
     * Limiting `event_retention` (`days` or `after_analysis`) also removes the sample
     * message text kept in every object's rolling summary, since the summary outlives
     * the events it was built from.
     *
     * `PATCH /v1/settings`
     *
     * @param SettingsUpdate $body
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return SettingsData
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function update(array $body, array $options = []): array
    {
        /** @var SettingsData $result */
        $result = $this->client->request('PATCH', '/v1/settings', [], null, $body, $options);

        return $result;
    }
}
