<?php

// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

declare(strict_types=1);

namespace SigWise\Resources;

use SigWise\SigWiseException;
use SigWise\Client;
use SigWise\ConnectionException;
use SigWise\Types;

/**
 * A signal is a question you ask about every object, such as "is this a scammer?"
 * (`noul`), "how trustworthy is this user?" (`score`) or "what is their buyer
 * intent?" (`choice`).
 *
 * @phpstan-import-type BackfillStatus from Types
 * @phpstan-import-type Signal from Types
 * @phpstan-import-type SignalBackfill from Types
 * @phpstan-import-type SignalInput from Types
 * @phpstan-import-type SignalList from Types
 */
final class Signals
{
    /** @internal Use the resources on SigWise\Client. */
    public function __construct(private readonly Client $client)
    {
    }

    /**
     * List signals.
     *
     * `GET /v1/signals`
     *
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return SignalList
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function list(array $options = []): array
    {
        /** @var SignalList $result */
        $result = $this->client->request('GET', '/v1/signals', [], null, null, $options);

        return $result;
    }

    /**
     * Create or update a signal.
     *
     * Creates the signal, or replaces its definition. `instructions` and `criteria`
     * are passed to the analyzer verbatim; the shape of `criteria` depends on `type`:
     *
     * | `type` | `criteria` |
     * |----------|------------------------------------------------------|
     * | `noul` | object with optional `true` / `false` descriptions |
     * | `score` | ordered array of level descriptions, low to high |
     * | `choice` | object mapping each option to a description or null |
     *
     * Creating a signal does not analyze existing objects unless the tenant setting
     * `auto_backfill_signals` is on; start a backfill explicitly with `POST
     * /v1/signals/{key}/backfill`.
     *
     * `PUT /v1/signals/{key}`
     *
     * @param SignalInput $body
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return Signal
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function upsert(string $key, array $body, array $options = []): array
    {
        /** @var Signal $result */
        $result = $this->client->request('PUT', '/v1/signals/{key}', ['key' => $key], null, $body, $options);

        return $result;
    }

    /**
     * Delete a signal.
     *
     * `DELETE /v1/signals/{key}`
     *
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return void
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function delete(string $key, array $options = []): void
    {
        $this->client->request('DELETE', '/v1/signals/{key}', ['key' => $key], null, null, $options);
    }

    /**
     * Get backfill estimate and progress.
     *
     * Returns how many existing objects have no answer for the signal and what
     * analyzing them would cost now, plus the progress of the most recent backfill
     * (`null` if none was started).
     *
     * `GET /v1/signals/{key}/backfill`
     *
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return BackfillStatus
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function getBackfill(string $key, array $options = []): array
    {
        /** @var BackfillStatus $result */
        $result = $this->client->request('GET', '/v1/signals/{key}/backfill', ['key' => $key], null, null, $options);

        return $result;
    }

    /**
     * Start a backfill.
     *
     * Re-analyzes, for this signal only, every existing object that has no answer for
     * it. Jobs run at bulk priority so they never delay live ingest. Each analysis is
     * billed. Returns `409` if the signal is disabled.
     *
     * `POST /v1/signals/{key}/backfill`
     *
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return SignalBackfill
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function startBackfill(string $key, array $options = []): array
    {
        /** @var SignalBackfill $result */
        $result = $this->client->request('POST', '/v1/signals/{key}/backfill', ['key' => $key], null, null, $options);

        return $result;
    }
}
