<?php

// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

declare(strict_types=1);

namespace SigWise\Resources;

use SigWise\SigWiseException;
use SigWise\Client;
use SigWise\ConnectionException;
use SigWise\Types;

/**
 * Analysis volume, spend and token usage over a date range.
 *
 * @phpstan-import-type Usage from Types as UsageData
 */
final class Usage
{
    /** @internal Use the resources on SigWise\Client. */
    public function __construct(private readonly Client $client)
    {
    }

    /**
     * Get usage.
     *
     * Analyses, spend and tokens over an inclusive UTC date range (at most 366 days),
     * with a zero-filled daily series and breakdowns by model, source (`async` /
     * `sync`) and signal. Defaults to the last 30 days.
     *
     * `GET /v1/usage`
     *
     * @param array{from?: string, to?: string} $params
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return UsageData
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function get(array $params = [], array $options = []): array
    {
        /** @var UsageData $result */
        $result = $this->client->request('GET', '/v1/usage', [], $params, null, $options);

        return $result;
    }
}
