<?php

// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

declare(strict_types=1);

namespace SigWise\Resources;

use SigWise\SigWiseException;
use SigWise\Client;
use SigWise\ConnectionException;
use SigWise\Types;

/**
 * Webhook endpoints receive a signed `POST` for the event types they subscribe to:
 * `analysis.completed` each time an analysis completes, and `rule.triggered` when
 * a rule with a webhook action fires.
 *
 * @phpstan-import-type DeliveryStatus from Types
 * @phpstan-import-type WebhookDelivery from Types
 * @phpstan-import-type WebhookDeliveryList from Types
 */
final class WebhookDeliveries
{
    /** @internal Use the resources on SigWise\Client. */
    public function __construct(private readonly Client $client)
    {
    }

    /**
     * List webhook deliveries.
     *
     * Recent deliveries, newest first. Filter with `status=dead` to inspect the
     * dead-letter queue.
     *
     * `GET /v1/webhook_deliveries`
     *
     * @param array{status?: DeliveryStatus, endpoint_id?: string, limit?: int} $params
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return WebhookDeliveryList
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function list(array $params = [], array $options = []): array
    {
        /** @var WebhookDeliveryList $result */
        $result = $this->client->request('GET', '/v1/webhook_deliveries', [], $params, null, $options);

        return $result;
    }

    /**
     * Replay a delivery.
     *
     * Re-queues a delivery (for example one in the dead-letter queue) for another
     * attempt.
     *
     * `POST /v1/webhook_deliveries/{delivery_id}/replay`
     *
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return WebhookDelivery
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function replay(string $deliveryId, array $options = []): array
    {
        /** @var WebhookDelivery $result */
        $result = $this->client->request('POST', '/v1/webhook_deliveries/{delivery_id}/replay', ['delivery_id' => $deliveryId], null, null, $options);

        return $result;
    }
}
