<?php

// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

declare(strict_types=1);

namespace SigWise\Resources;

use SigWise\SigWiseException;
use SigWise\Client;
use SigWise\ConnectionException;
use SigWise\Types;

/**
 * Webhook endpoints receive a signed `POST` for the event types they subscribe to:
 * `analysis.completed` each time an analysis completes, and `rule.triggered` when
 * a rule with a webhook action fires.
 *
 * @phpstan-import-type WebhookEndpoint from Types
 * @phpstan-import-type WebhookEndpointCreate from Types
 * @phpstan-import-type WebhookEndpointCreated from Types
 * @phpstan-import-type WebhookEndpointList from Types
 * @phpstan-import-type WebhookEndpointUpdate from Types
 */
final class Webhooks
{
    /** @internal Use the resources on SigWise\Client. */
    public function __construct(private readonly Client $client)
    {
    }

    /**
     * List webhook endpoints.
     *
     * `GET /v1/webhooks`
     *
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return WebhookEndpointList
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function list(array $options = []): array
    {
        /** @var WebhookEndpointList $result */
        $result = $this->client->request('GET', '/v1/webhooks', [], null, null, $options);

        return $result;
    }

    /**
     * Register a webhook endpoint.
     *
     * Registers an endpoint and returns its signing secret. **The secret is shown only
     * once**; store it to verify deliveries.
     *
     * `POST /v1/webhooks`
     *
     * @param WebhookEndpointCreate $body
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return WebhookEndpointCreated
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function create(array $body, array $options = []): array
    {
        /** @var WebhookEndpointCreated $result */
        $result = $this->client->request('POST', '/v1/webhooks', [], null, $body, $options);

        return $result;
    }

    /**
     * Get a webhook endpoint.
     *
     * `GET /v1/webhooks/{endpoint_id}`
     *
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return WebhookEndpoint
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function get(string $endpointId, array $options = []): array
    {
        /** @var WebhookEndpoint $result */
        $result = $this->client->request('GET', '/v1/webhooks/{endpoint_id}', ['endpoint_id' => $endpointId], null, null, $options);

        return $result;
    }

    /**
     * Update a webhook endpoint.
     *
     * Omitted fields are left unchanged.
     *
     * `PATCH /v1/webhooks/{endpoint_id}`
     *
     * @param WebhookEndpointUpdate $body
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return WebhookEndpoint
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function update(string $endpointId, array $body, array $options = []): array
    {
        /** @var WebhookEndpoint $result */
        $result = $this->client->request('PATCH', '/v1/webhooks/{endpoint_id}', ['endpoint_id' => $endpointId], null, $body, $options);

        return $result;
    }

    /**
     * Delete a webhook endpoint.
     *
     * Removes the endpoint and its deliveries.
     *
     * `DELETE /v1/webhooks/{endpoint_id}`
     *
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return void
     * @throws SigWiseException
     * @throws ConnectionException
     */
    public function delete(string $endpointId, array $options = []): void
    {
        $this->client->request('DELETE', '/v1/webhooks/{endpoint_id}', ['endpoint_id' => $endpointId], null, null, $options);
    }
}
