<?php

// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

declare(strict_types=1);

namespace SigWise;

/**
 * SigWise API client.
 *
 *     $sigwise = new SigWise\Client('your_key_id', 'your_secret');
 *     $object = $sigwise->objects->get('user-42');
 *
 * Every request is signed with the API key's secret: the client sends the key
 * ID and a short-lived HS256 token bound to the request's method and path. The
 * secret itself is never sent.
 */
final class Client
{
    public const VERSION = '1.0.4';
    public const DEFAULT_BASE_URL = 'https://api.sigwise.ai';

    /** How long each request token is valid for, in seconds (the API allows 300). */
    private const TOKEN_TTL = 60;
    private const RETRY_STATUSES = [408, 429, 500, 502, 503, 504];
    private const IDEMPOTENT = ['GET', 'HEAD', 'PUT', 'DELETE', 'OPTIONS'];

    /** The authenticated principal and tenant settings. */
    public readonly Resources\Me $me;
    /** An object is anything you want answers about: a user, a listing, an order. */
    public readonly Resources\Overview $overview;
    /** An object is anything you want answers about: a user, a listing, an order. */
    public readonly Resources\Objects $objects;
    /** Events and messages are the evidence an object's answers are computed from. */
    public readonly Resources\Playground $playground;
    /** Events and messages are the evidence an object's answers are computed from. */
    public readonly Resources\Events $events;
    /** A signal is a question you ask about every object, such as "is this a scammer?" (`noul`), "how trustworthy is this user?" (`score`) or "what is their buyer intent?" (`choice`). */
    public readonly Resources\Signals $signals;
    /** The authenticated principal and tenant settings. */
    public readonly Resources\Settings $settings;
    /** Webhook endpoints receive a signed `POST` for the event types they subscribe to: `analysis.completed` each time an analysis completes, and `rule.triggered` when a rule with a webhook action fires. */
    public readonly Resources\Webhooks $webhooks;
    /** Webhook endpoints receive a signed `POST` for the event types they subscribe to: `analysis.completed` each time an analysis completes, and `rule.triggered` when a rule with a webhook action fires. */
    public readonly Resources\WebhookDeliveries $webhookDeliveries;
    /** A rule fires an action (email, Slack or webhook) when an object's signal values cross a line you care about, such as `is_scammer >= 90`. */
    public readonly Resources\Rules $rules;
    /** A rule fires an action (email, Slack or webhook) when an object's signal values cross a line you care about, such as `is_scammer >= 90`. */
    public readonly Resources\RuleFirings $ruleFirings;
    /** Create, rotate and revoke the keys your integrations sign requests with. */
    public readonly Resources\ApiKeys $apiKeys;
    /** Prepaid balance, the billing ledger, and card top-ups. */
    public readonly Resources\Billing $billing;
    /** Analysis volume, spend and token usage over a date range. */
    public readonly Resources\Usage $usage;

    private readonly string $apiKey;
    private readonly string $secret;
    private readonly string $baseUrl;
    private readonly float $timeout;
    private readonly int $maxRetries;
    /** @var array<string, string> */
    private readonly array $headers;

    /**
     * @param string|null $apiKey The API key ID. Defaults to SIGWISE_API_KEY.
     * @param string|null $secret The key's signing secret. Defaults to SIGWISE_SECRET.
     * @param array{base_url?: string, timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     *     base_url defaults to SIGWISE_BASE_URL, then the production API; timeout is in seconds (30);
     *     max_retries applies to idempotent requests only (2).
     */
    public function __construct(?string $apiKey = null, ?string $secret = null, array $options = [])
    {
        $apiKey = $apiKey ?: (getenv('SIGWISE_API_KEY') ?: null);
        $secret = $secret ?: (getenv('SIGWISE_SECRET') ?: null);
        if ($apiKey === null || $secret === null) {
            throw new \InvalidArgumentException(
                'SigWise: an API key and its secret are required. Pass them to the constructor or set SIGWISE_API_KEY and SIGWISE_SECRET.'
            );
        }
        $this->apiKey = $apiKey;
        $this->secret = $secret;
        $base = $options['base_url'] ?? (getenv('SIGWISE_BASE_URL') ?: self::DEFAULT_BASE_URL);
        $this->baseUrl = rtrim($base, '/');
        $this->timeout = (float) ($options['timeout'] ?? 30);
        $this->maxRetries = $options['max_retries'] ?? 2;
        $this->headers = $options['headers'] ?? [];

        $this->me = new Resources\Me($this);
        $this->overview = new Resources\Overview($this);
        $this->objects = new Resources\Objects($this);
        $this->playground = new Resources\Playground($this);
        $this->events = new Resources\Events($this);
        $this->signals = new Resources\Signals($this);
        $this->settings = new Resources\Settings($this);
        $this->webhooks = new Resources\Webhooks($this);
        $this->webhookDeliveries = new Resources\WebhookDeliveries($this);
        $this->rules = new Resources\Rules($this);
        $this->ruleFirings = new Resources\RuleFirings($this);
        $this->apiKeys = new Resources\ApiKeys($this);
        $this->billing = new Resources\Billing($this);
        $this->usage = new Resources\Usage($this);
    }

    /**
     * Signs the HS256 JWT that authenticates one request: kid names the key,
     * iat/exp bound its lifetime, and htm/htu bind it to the method and path.
     */
    public static function signRequestToken(string $apiKey, string $secret, string $method, string $path, ?int $now = null): string
    {
        $now ??= time();
        $claims = [
            'iat' => $now,
            'exp' => $now + self::TOKEN_TTL,
            'jti' => bin2hex(random_bytes(16)),
            'htm' => strtoupper($method),
        ];
        // The server compares htu with the decoded path, so only bind paths it
        // can read back unchanged.
        if (strpbrk($path, '?#') === false) {
            $claims['htu'] = $path;
        }
        $header = self::base64url(json_encode(['alg' => 'HS256', 'typ' => 'JWT', 'kid' => $apiKey], JSON_THROW_ON_ERROR));
        $payload = self::base64url(json_encode($claims, JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES));
        $signature = self::base64url(hash_hmac('sha256', $header . '.' . $payload, $secret, true));

        return $header . '.' . $payload . '.' . $signature;
    }

    /**
     * Sends a request. Used by the resource classes.
     *
     * @internal
     * @param array<string, string> $pathParams
     * @param array<string, mixed>|null $query
     * @param array<mixed>|object|null $body
     * @param array{timeout?: float|int, max_retries?: int, headers?: array<string, string>} $options
     * @return mixed The decoded JSON body, or null for an empty response.
     * @throws SigWiseException for an error response
     * @throws ConnectionException when no response arrives
     */
    public function request(string $method, string $path, array $pathParams = [], ?array $query = null, array|object|null $body = null, array $options = []): mixed
    {
        $method = strtoupper($method);
        if ($method === '') {
            throw new \InvalidArgumentException('SigWise: method is required');
        }
        $rawPath = $path;
        $encodedPath = $path;
        foreach ($pathParams as $name => $value) {
            if ($value === '') {
                throw new \InvalidArgumentException("SigWise: {$name} is required");
            }
            $rawPath = str_replace('{' . $name . '}', $value, $rawPath);
            $encodedPath = str_replace('{' . $name . '}', rawurlencode($value), $encodedPath);
        }

        $params = ['api_key' => $this->apiKey];
        foreach ($query ?? [] as $key => $value) {
            if ($value === null) {
                continue;
            }
            $params[$key] = is_bool($value) ? ($value ? 'true' : 'false') : $value;
        }
        $url = $this->baseUrl . $encodedPath . '?' . http_build_query($params, '', '&', PHP_QUERY_RFC3986);

        $payload = null;
        if ($body !== null) {
            // An empty PHP array would encode as [] where the API expects {}.
            $payload = $body === [] ? '{}' : json_encode($body, JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
        }

        $retries = in_array($method, self::IDEMPOTENT, true) ? ($options['max_retries'] ?? $this->maxRetries) : 0;
        $timeout = (float) ($options['timeout'] ?? $this->timeout);
        for ($attempt = 0; ; $attempt++) {
            $headers = array_merge(
                ['Accept' => 'application/json', 'User-Agent' => 'sigwise/sdk/' . self::VERSION . ' (php)'],
                $this->headers,
                $options['headers'] ?? [],
                ['Authorization' => 'Bearer ' . self::signRequestToken($this->apiKey, $this->secret, $method, $rawPath)],
            );
            if ($payload !== null) {
                $headers['Content-Type'] = 'application/json';
            }

            try {
                [$status, $responseHeaders, $raw] = $this->send($method, $url, $headers, $payload, $timeout);
            } catch (ConnectionException $e) {
                if ($attempt >= $retries) {
                    throw $e;
                }
                self::backoff($attempt, null);
                continue;
            }

            if ($status >= 200 && $status < 300) {
                return self::decode($status, $responseHeaders, $raw);
            }
            if ($attempt < $retries && in_array($status, self::RETRY_STATUSES, true)) {
                self::backoff($attempt, $responseHeaders['retry-after'] ?? null);
                continue;
            }
            $decoded = self::decode($status, $responseHeaders, $raw);
            $error = is_array($decoded) && is_array($decoded['error'] ?? null) ? $decoded['error'] : [];
            throw new SigWiseException(
                $status,
                is_string($error['code'] ?? null) ? $error['code'] : 'http_' . $status,
                is_string($error['message'] ?? null) ? $error['message'] : "{$method} {$rawPath} returned {$status}",
                $decoded,
                $responseHeaders,
            );
        }
    }

    /**
     * @param non-empty-string $method
     * @param array<string, string> $headers
     * @return array{int, array<string, string>, string}
     */
    private function send(string $method, string $url, array $headers, ?string $payload, float $timeout): array
    {
        $lines = [];
        foreach ($headers as $name => $value) {
            $lines[] = $name . ': ' . $value;
        }
        $responseHeaders = [];
        $ch = curl_init($url);
        curl_setopt_array($ch, [
            CURLOPT_CUSTOMREQUEST => $method,
            CURLOPT_HTTPHEADER => $lines,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_TIMEOUT_MS => (int) ($timeout * 1000),
            CURLOPT_CONNECTTIMEOUT_MS => (int) (min($timeout, 10.0) * 1000),
            CURLOPT_HEADERFUNCTION => static function (\CurlHandle $ch, string $line) use (&$responseHeaders): int {
                $parts = explode(':', $line, 2);
                if (count($parts) === 2) {
                    $responseHeaders[strtolower(trim($parts[0]))] = trim($parts[1]);
                }
                return strlen($line);
            },
        ]);
        if ($payload !== null) {
            curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);
        }
        $raw = curl_exec($ch);
        if ($raw === false) {
            $message = curl_error($ch);
            curl_close($ch);
            throw new ConnectionException("SigWise: {$method} request failed: {$message}");
        }
        $status = (int) curl_getinfo($ch, CURLINFO_RESPONSE_CODE);
        curl_close($ch);

        return [$status, $responseHeaders, (string) $raw];
    }

    /** @param array<string, string> $headers */
    private static function decode(int $status, array $headers, string $raw): mixed
    {
        if ($status === 204 || $raw === '') {
            return null;
        }
        if (str_contains($headers['content-type'] ?? '', 'json')) {
            try {
                return json_decode($raw, true, 512, JSON_THROW_ON_ERROR);
            } catch (\JsonException) {
                return $raw;
            }
        }
        return $raw;
    }

    private static function backoff(int $attempt, ?string $retryAfter): void
    {
        if ($retryAfter !== null && is_numeric($retryAfter) && (float) $retryAfter >= 0) {
            usleep((int) (min((float) $retryAfter, 60.0) * 1_000_000));
            return;
        }
        $base = min(0.5 * (2 ** $attempt), 8.0);
        usleep((int) (($base / 2 + (mt_rand() / mt_getrandmax()) * $base / 2) * 1_000_000));
    }

    private static function base64url(string $data): string
    {
        return rtrim(strtr(base64_encode($data), '+/', '-_'), '=');
    }
}
