<?php

// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

declare(strict_types=1);

namespace SigWise;

/** The request never got a response: a network error or a timeout. */
class ConnectionException extends \RuntimeException
{
}
