<?php

// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

declare(strict_types=1);

namespace SigWise;

/** The API answered with an error status. */
class SigWiseException extends \RuntimeException
{
    /**
     * @param int $status The HTTP status code.
     * @param string $errorCode The machine-readable error code, e.g. not_found.
     * @param mixed $body The decoded response body.
     * @param array<string, string> $headers The response headers, lower-cased.
     */
    public function __construct(
        public readonly int $status,
        public readonly string $errorCode,
        string $message,
        public readonly mixed $body = null,
        public readonly array $headers = [],
    ) {
        parent::__construct($message, $status);
    }
}
