<?php

// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

declare(strict_types=1);

namespace SigWise;

/**
 * The shapes of request and response bodies, for PHPStan and Psalm. At runtime
 * they are plain arrays: requests take arrays of these shapes and responses decode
 * to them. Import one with @phpstan-import-type Name from \SigWise\Types.
 *
 * @phpstan-type ApiKey array{id: string, key: string, name: string, status: ApiKeyStatus, has_secret: bool, legacy?: bool, legacy_preview?: string, created_at: string, last_used_at?: string, legacy_used_at?: string}
 * @phpstan-type ApiKeyCreate array{name?: string}
 * @phpstan-type ApiKeyList array{api_keys: list<ApiKey>}
 * @phpstan-type ApiKeySecret array{api_key: ApiKey, key: string, secret: string, note: string}
 * @phpstan-type ApiKeyStatus 'active'|'inactive'|'revoked'
 * @phpstan-type ApiKeyUpdate array{name?: string, status?: 'active'|'inactive'}
 * @phpstan-type ActionConfig array<string, mixed>
 * @phpstan-type ActionType 'email'|'slack'|'webhook'
 * @phpstan-type AnalysisCompletedEvent array{event: 'analysis.completed', object_id: string, tenant_id: string, model: string, occurred_at: string, answers: list<Answer>}
 * @phpstan-type AnalyzeAllScheduled array{scheduled: int, analysis_status: 'scheduled'}
 * @phpstan-type AnalyzeScheduled array{object_id: string, analysis_status: 'scheduled'}
 * @phpstan-type Answer array{signal: string, type: SignalType, noul?: float|int, choice?: string, score?: float|int, probabilities?: array<string, float|int>, confidence?: float|int}
 * @phpstan-type BackfillEstimate array{objects: int, estimated_cost_micros: int}
 * @phpstan-type BackfillStatus array{estimate: BackfillEstimate, backfill: SignalBackfill|null}
 * @phpstan-type Balance array{balance_cents: int, currency: string, metering_enabled: bool, enforcement: string, self_serve_topup: bool, low_balance_threshold_cents: int, topup_min_cents?: int, topup_max_cents?: int}
 * @phpstan-type CategoryCount array{name: string, count: int}
 * @phpstan-type CheckoutCreate array{amount_cents: int}
 * @phpstan-type CheckoutSession array{id: string, url: string}
 * @phpstan-type CheckoutStatus array{id: string, status: 'pending'|'credited', amount_cents?: int, balance_after_cents?: int}
 * @phpstan-type CompactedState array{total_events: int, messages: int, actions: int, by_action?: array<string, int>, sample_messages?: list<string>, first_seen: string, updated_at: string}
 * @phpstan-type DeliveryStatus 'pending'|'delivering'|'delivered'|'dead'
 * @phpstan-type Event array{type: EventType, name?: string, content?: string, metadata?: Metadata, occurred_at: string}
 * @phpstan-type EventInput array{type: EventType, name?: string, content?: string, metadata?: Metadata, occurred_at?: string}
 * @phpstan-type EventList array{events: list<Event>}
 * @phpstan-type EventType 'event'|'message'
 * @phpstan-type IngestAccepted array{object_id: string, accepted: int, analysis_status: 'scheduled', analysis_delay_ms: int}
 * @phpstan-type IngestRequest array{object_type?: string, events: list<EventInput>, wait?: bool, signals?: list<string>, include_history?: bool}
 * @phpstan-type LedgerEntry array{id: string, delta_cents: int, balance_after_cents: int, delta_micros: int, balance_after_micros: int, reason: string, model?: string, object_id?: string, cost_usd?: float|int, cost_margin?: float|int, input_tokens?: int, output_tokens?: int, payment_ref?: string, created_at: string}
 * @phpstan-type LedgerPage array{entries: list<LedgerEntry>, next_cursor: string}
 * @phpstan-type Me array{auth_type: 'tenant'|'console', tenant_id: string, tenant_name: string, user_id?: string, email?: string, role?: string, onboarded?: bool}
 * @phpstan-type Metadata array<string, mixed>
 * @phpstan-type ModerationVerdict array{object_id: string, accepted: int, analyzed: bool, history_included: bool, model: string, latency_ms: int, answers: list<Answer>, reason?: string}
 * @phpstan-type ObjectAnalysis array{object_id: string, event_count: int, analysis: list<SignalResult>, pending: list<string>}
 * @phpstan-type ObjectList array{objects: list<ObjectSummary>, limit: int, offset: int, next_cursor?: string}
 * @phpstan-type ObjectState array{object_id: string, compacted_events: int, compacted_through?: string|null, compacted_state?: CompactedState|null, last_analyzed_at?: string|null}
 * @phpstan-type ObjectSummary array{object_id: string, object_type: string, display_name?: string, event_count: int, last_seen: string, analysis: list<SignalResult>, pending: list<string>}
 * @phpstan-type Overview array{objects: int, signals: int, analyzed_pct: float|int, events_today: int, flagged: int, signal_summary: list<SignalSummary>, categories: list<CategoryCount>, top_risk: list<RiskyObject>}
 * @phpstan-type RiskyObject array{object_id: string, display_name?: string, risk: float|int}
 * @phpstan-type Rule array{id: string, name: string, when: string, action_type: ActionType, action_config: ActionConfig, enabled: bool, cooldown_seconds: int, created_at: string, updated_at: string}
 * @phpstan-type RuleCreate array{name?: string, when: string, action_type: ActionType, action_config: ActionConfig, enabled?: bool, cooldown_seconds?: int}
 * @phpstan-type RuleFiring array{id: string, rule_id: string, object_id: string, matched_when: string, signal_values?: array<string, mixed>, action_type: ActionType, status: 'dispatched'|'error', detail?: string, fired_at: string}
 * @phpstan-type RuleFiringList array{firings: list<RuleFiring>}
 * @phpstan-type RuleList array{rules: list<Rule>}
 * @phpstan-type RuleTriggeredEvent array{event: 'rule.triggered', rule_id: string, rule_name?: string, tenant_id: string, object_id: string, matched_when: string, model?: string, occurred_at: string, values: list<Answer>}
 * @phpstan-type RuleUpdate array{name?: string, when?: string, action_type?: ActionType, action_config?: ActionConfig, enabled?: bool, cooldown_seconds?: int}
 * @phpstan-type Settings array{auto_backfill_signals: bool}
 * @phpstan-type SettingsUpdate array{auto_backfill_signals?: bool}
 * @phpstan-type Signal array{key: string, type: SignalType, instructions: mixed, criteria?: mixed, enabled: bool, created_at: string, updated_at: string, backfill?: SignalBackfill}
 * @phpstan-type SignalBackfill array{signal_key: string, status: 'running'|'done', total: int, completed: int, pending: int, started_at: string}
 * @phpstan-type SignalInput array{type: SignalType, instructions: mixed, criteria?: mixed, enabled?: bool}
 * @phpstan-type SignalList array{signals: list<Signal>}
 * @phpstan-type SignalResult array{key: string, type: SignalType, noul?: float|int, choice?: string, score?: float|int, probabilities?: array<string, float|int>, confidence?: float|int, model?: string, computed_at: string}
 * @phpstan-type SignalSummary array{key: string, type: SignalType, total: int, avg?: float|int, high?: int, high_pct?: float|int, choices?: array<string, float|int>}
 * @phpstan-type SignalType 'noul'|'choice'|'score'
 * @phpstan-type Usage array{from: string, to: string, currency: string, metering_enabled: bool, balance_cents: int, burn_rate_micros_per_day: int, runway_days?: float|int, totals: UsageTotals, series: list<UsageDay>, by_model: list<UsageBreakdown>, by_source: list<UsageBreakdown>, by_signal: list<UsageSignal>}
 * @phpstan-type UsageBreakdown array{key: string, analyses: int, spend_micros: int, input_tokens: int, output_tokens: int}
 * @phpstan-type UsageDay array{date: string, analyses: int, async: int, sync: int, spend_micros: int}
 * @phpstan-type UsageSignal array{signal: string, analyses: int}
 * @phpstan-type UsageTotals array{analyses: int, spend_micros: int, input_tokens: int, output_tokens: int}
 * @phpstan-type WebhookDelivery array{id: string, endpoint_id: string, event_type: 'analysis.completed'|'rule.triggered', object_id?: string, status: DeliveryStatus, attempts: int, max_attempts: int, last_status_code?: int, last_error?: string, run_after: string, delivered_at?: string, created_at: string, payload?: array<string, mixed>}
 * @phpstan-type WebhookDeliveryList array{deliveries: list<WebhookDelivery>}
 * @phpstan-type WebhookEndpoint array{id: string, url: string, description: string, enabled: bool, signal_keys: list<string>, events: list<WebhookEventType>, created_at: string, updated_at: string}
 * @phpstan-type WebhookEndpointCreate array{url: string, description?: string, signal_keys?: list<string>, events?: list<WebhookEventType>, enabled?: bool}
 * @phpstan-type WebhookEndpointCreated array{endpoint: WebhookEndpoint, secret: string, note: string}
 * @phpstan-type WebhookEndpointList array{webhooks: list<WebhookEndpoint>}
 * @phpstan-type WebhookEndpointUpdate array{url?: string, description?: string, signal_keys?: list<string>, events?: list<WebhookEventType>, enabled?: bool}
 * @phpstan-type WebhookEventType 'analysis.completed'|'rule.triggered'
 */
final class Types
{
}
