<?php

// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

declare(strict_types=1);

namespace SigWise;

/** The signature, timestamp or payload of a webhook delivery is not valid. */
final class WebhookVerificationException extends \RuntimeException
{
}
