<?php

// Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

declare(strict_types=1);

namespace SigWise;

/**
 * Verifies and parses webhook deliveries.
 * @phpstan-import-type AnalysisCompletedEvent from Types
 * @phpstan-import-type RuleTriggeredEvent from Types
 */
final class Webhook
{
    /** How old a delivery's timestamp may be, in seconds. */
    public const DEFAULT_TOLERANCE = 300;

    /**
     * Verifies a webhook delivery: $signature (the X-Webhook-Signature header)
     * must be the HMAC-SHA256 of "<timestamp>.<payload>" keyed with the
     * endpoint secret, and $timestamp (X-Webhook-Timestamp) must be recent.
     * Pass the raw body, exactly as received.
     *
     * @throws WebhookVerificationException
     */
    public static function verifySignature(string $payload, ?string $signature, ?string $timestamp, string $secret, int $tolerance = self::DEFAULT_TOLERANCE, ?int $now = null): void
    {
        if ($signature === null || $signature === '' || $timestamp === null || $timestamp === '') {
            throw new WebhookVerificationException('missing signature or timestamp header');
        }
        if (!ctype_digit($timestamp)) {
            throw new WebhookVerificationException('invalid timestamp');
        }
        $now ??= time();
        if ($tolerance > 0 && abs($now - (int) $timestamp) > $tolerance) {
            throw new WebhookVerificationException('timestamp outside the tolerance');
        }
        $expected = 'sha256=' . hash_hmac('sha256', $timestamp . '.' . $payload, $secret);
        if (!hash_equals($expected, $signature)) {
            throw new WebhookVerificationException('signature mismatch');
        }
    }

    /**
     * Verifies a webhook delivery (see verifySignature) and decodes its body.
     *
     * @return AnalysisCompletedEvent|RuleTriggeredEvent
     * @throws WebhookVerificationException
     */
    public static function constructEvent(string $payload, ?string $signature, ?string $timestamp, string $secret, int $tolerance = self::DEFAULT_TOLERANCE, ?int $now = null): array
    {
        self::verifySignature($payload, $signature, $timestamp, $secret, $tolerance, $now);
        try {
            $event = json_decode($payload, true, 512, JSON_THROW_ON_ERROR);
        } catch (\JsonException) {
            throw new WebhookVerificationException('payload is not valid JSON');
        }
        if (!is_array($event)) {
            throw new WebhookVerificationException('payload is not a JSON object');
        }
        /** @var AnalysisCompletedEvent|RuleTriggeredEvent $event */
        return $event;
    }
}
